[package]
name = "websocket-motoko"
version = "0.0.1"
description = "IC WebSocket Motoko Impimentetion"
repository = ""
keywords = [ ]
license = "MIT"

[dependencies]
base = "0.9.1"
ic-certification = "0.1.1"
sha2 = "0.0.2"
cbor = "0.1.3"
ic-websocket-cdk-mo = "https://github.com/omnia-network/ic-websocket-cdk-mo#e930f81d0e948ae76f583d46ff3be0f4ba043bc3"
candid = "1.0.2"
