[package]
name = "websocket-motoko"
version = "0.0.1"
description = "IC WebSocket Motoko Impimentetion"
repository = ""
keywords = [ ]
license = "MIT"

[dependencies]
base = "0.9.1"
ic-certification = "0.1.1"
sha2 = "0.0.2"
cbor = "0.1.3"
ic-websocket-cdk-mo = "https://github.com/omnia-network/ic-websocket-cdk-mo#a229d4a6d95987b4b1d46e9c5e7fde6d896fa118"
candid = "1.0.2"
